apiVersion: v1
kind: Pod

metadata:
  name: imageprocessingapi

spec:
  containers:
  - name: imageprocessingapi
    image: image_processing_api:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 5000